# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xYv6nscrCw5qNFvO9FBc8rrZxyAarQjK
"""

import random
print("******************************************************************************")
print("*                *   ROCK    *    PAPER   *   SCISSOR    *                   *")
print("*****************************************************************************")
print(" LETS START THE GAME!!..... ")
point=0
ai=0
hs=0
cs=0
ma=0
while(True):
  if(ma>5):
    print("########################################")
    print("Total Match:",ma)
    print("Human Score:",hs)
    print("Computer SCore:",cs)
    if(hs>cs):
      print("Congrats You Win")
    elif(cs>hs):
        print("AI Won..... Better Luck Next Time")
    else:
        print("Match Draw")
    print("########################################")
  c=input("  Choose the option: Paper->p  Rock->r  Scissor->s Stop->stop: ")
  if(c=="p"):
    print("Paper")
    point=10+random.randint(1,3)
    match point:
      case 11:
        ma=ma+1
        hs=hs+1
        print("Human: Paper", "AI: Rock")
        print("Match: ",ma,"Human Score:",hs,"AI Score:",cs,)
        print("Human: wins","AI: lost the match")
        print("______________________________")
      case 12:
        ma=ma+1
        cs=cs+1
        print("Human: Paper", "AI: Scissor")
        print("Match: ",ma,"Human Score:",hs,"AI Score:",cs,)
        print("Human: lost","AI: wins the match")
        print("______________________________")
      case 13:
        ma=ma+1
        hs=hs+1
        cs=cs+1
        print("Human: Paper", "AI:paper ")
        print("Match: ",ma,"Human Score:",hs,"AI Score:",cs,)
        print("Mtach Draw")
        print("______________________________")
  elif(c=="r"):
    print("Rock")
    point=20+random.randint(1,3)
    match point:
      case 21:
        ma=ma+1
        hs=hs+1
        print("Human: Rock", "AI: Scissor")
        print("Match: ",ma,"Human Score:",hs,"AI Score:",cs,)
        print("Human: wins","AI: lost the match")
        print("______________________________")
      case 22:
        ma=ma+1
        cs=cs+1
        print("Human: Rock", "AI: Paper")
        print("Human: lost","AI: wins the match")
        print("Match: ",ma,"Human Score:",hs,"AI Score:",cs,)
        print("______________________________")
      case 23:
        ma=ma+1
        hs=hs+1
        cs=cs+1
        print("Human: Rockr", "AI:Rock ")
        print("Match: ",ma,"Human Score:",hs,"AI Score:",cs,)
        print("Mtach Draw")
        print("______________________________")
  elif(c=="s"):
    print("Scissor")
    point=30+random.randint(1,3)
    match point:
      case 31:
        ma=ma+1
        hs=hs+1
        print("Human: Scissor", "AI: Paper")
        print("Match: ",ma,"Human Score:",hs,"AI Score:",cs,)
        print("Human: wins","AI: lost the match")
        print("______________________________")
      case 32:
        ma=ma+1
        cs=cs+1
        print("Human: Scissor", "AI: Rock")
        print("Match: ",ma,"Human Score:",hs,"AI Score:",cs,)
        print("Human: lost","AI: wins the match")
        print("______________________________")
      case 33:
        ma=ma+1
        hs=hs+1
        cs=cs+1
        print("Human: Scissor", "AI:Scissor ")
        print("Match: ",ma,"Human Score:",hs,"AI Score:",cs,)
        print("Mtach Draw")
        print("______________________________")
  elif(c=="stop"):
    break
print("program end")

